name: Dife Auto Verification CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Apt
        run: |
          sudo apt-get update

      - name: Install OpenSSL
        run: sudo apt-get install openssl

      - name: Create .env file
        run: |
          mkdir -p ai
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > dife_verification/.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > dife_verification/.env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" > dife_verification/.env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" > dife_verification/.env
          echo "S3_IMAGE_KEY=${{ secrets.S3_IMAGE_KEY }}" > dife_verification/.env

      - name: Upload AI directory to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "ai"
          target: "/home/ubuntu"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/dife_verification
            docker-compose down -v   
            docker-compose up -d --build 
